In [15]:
import numpy as np
mydata = np.arange(0,20)
type(mydata)

numpy.ndarray

In [16]:
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
# np.reshape(*, *, 'C')  C --> C language
#    arranged in rows
# np.reshape(*, *, 'F')   F --> Fortran
#    arranged in columns

# np.shape(mydata, (5,4), order='C')  OR
np.reshape(mydata, (5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
np.reshape(mydata, (5,4), order='F')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [12]:
MATR1 = np.reshape(mydata, (5,4), order='C')
MATR1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
# Get to the number 10
MATR1[2,2]

10

In [17]:
# Object oriented concept
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
mydata.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
mydata.reshape(5,4,order='F')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [20]:
l1 = ["I", "am", "happy"]
l2 = ["What", "a", "day"]
l3 = [1, 2, 3]

In [22]:
np.array([l1, l2, l3])

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], 
      dtype='<U5')

In [23]:
print(np.array([l1, l2, l3]))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]
