In [1]:
# Module: A module is a file containing python definitions, functions and statements. 
# Putting code into modules is useful because of the ability to import the module functionality into ur script or IPython 
# session.


# Package:  A package is just a way of collecting related modules together with in a single tree-like hierarchy. 
#  Very complex packages like NumPy and SciPy have hundreds of individual modules so putting them in to a directory-like 
#  structure keep things organized and avoid name collisions

In [3]:
import scrapy

ImportError: No module named 'scrapy'

In [2]:
# conda install scrapy

In [6]:
#scrapy package
import scrapy

In [7]:
# cramler module, CrawlerProcess is a class/function
from scrapy.crawler import CrawlerProcess

In [8]:
# CrawlerProcess.crawl

---

In [9]:
# numpy arrays: supports same datatypes

In [10]:
import numpy as np

In [20]:
b = np.array([2,4,True,"hi"])

array(['2', '4', 'True', 'hi'], 
      dtype='<U11')

In [21]:
b

array(['2', '4', 'True', 'hi'], 
      dtype='<U11')

In [14]:
ll = [44,55,True,"hi"]

In [15]:
bb = np.array(ll)

In [23]:
print(bb)

['44' '55' 'True' 'hi']


In [24]:
np.array([5,6,7.88,3])

array([ 5.  ,  6.  ,  7.88,  3.  ])

---

In [25]:
# Array slicing

In [27]:
a = np.array([3, 5, 6,7 ,8,56,343,5,67,89])

In [28]:
a

array([  3,   5,   6,   7,   8,  56, 343,   5,  67,  89])

In [30]:
# array slicing does Not create another array it points to same array, any modifications to sliced array will modify original 
#  array
a[2:6]

array([ 6,  7,  8, 56])

In [36]:
b = a[2:6]

In [38]:
b

array([ 6,  7,  8, 56])

In [40]:
b[:] = 1111

In [41]:
b

array([1111, 1111, 1111, 1111])

In [42]:
a

array([   3,    5, 1111, 1111, 1111, 1111,  343,    5,   67,   89])

In [44]:
# To copy array
c = a.copy()

In [45]:
c

array([   3,    5, 1111, 1111, 1111, 1111,  343,    5,   67,   89])

In [46]:
c[1] = 44444

In [47]:
c

array([    3, 44444,  1111,  1111,  1111,  1111,   343,     5,    67,    89])

In [48]:
a

array([   3,    5, 1111, 1111, 1111, 1111,  343,    5,   67,   89])