## Section 4 Homework data

Dear Student,

Welcome to the dataset for the homework exercise.

**Instructions for this dataset:**

You have only been supplied vectors. You will need to create the matrices yourself.

Matrices:
 - FreeThrows
 - FreeThrowAttempts

Sincerely,

Kirill Eremenko

[Super Data Science](http://www.superdatascience.com)

Copyright: These datasets were prepared using publicly available data.
           However, theses scripts are subject to Copyright Laws. 
           If you wish to use these R scripts outside of the R Programming Course
           by Kirill Eremenko, you may do so by referencing www.superdatascience.com in your work.

*Comments:*
Seasons are labeled based on the first year in the season
E.g. the 2012-2013 season is preseneted as simply 2012

Notes and Corrections to the data:
 - Kevin Durant: 2006 - College Data Used
 - Kevin Durant: 2005 - Proxied With 2006 Data
 - Derrick Rose: 2012 - Did Not Play
 - Derrick Rose: 2007 - College Data Used
 - Derrick Rose: 2006 - Proxied With 2007 Data
 - Derrick Rose: 2005 - Proxied With 2007 Data

In [15]:
#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Free Throws
KobeBryant_FT = [696,667,623,483,439,483,381,525,18,196]
JoeJohnson_FT = [261,235,316,299,220,195,158,132,159,141]
LeBronJames_FT = [601,489,549,594,593,503,387,403,439,375]
CarmeloAnthony_FT = [573,459,464,371,508,507,295,425,459,189]
DwightHoward_FT = [356,390,529,504,483,546,281,355,349,143]
ChrisBosh_FT = [474,463,472,504,470,384,229,241,223,179]
ChrisPaul_FT = [394,292,332,455,161,337,260,286,295,289]
KevinDurant_FT = [209,209,391,452,756,594,431,679,703,146]
DerrickRose_FT = [146,146,146,197,259,476,194,0,27,152]
DwayneWade_FT = [629,432,354,590,534,494,235,308,189,284]

#Matrix
#
#
import numpy as np
#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

FreeThrows = np.array([KobeBryant_FT, JoeJohnson_FT, LeBronJames_FT, CarmeloAnthony_FT, DwightHoward_FT, ChrisBosh_FT, ChrisPaul_FT, KevinDurant_FT, DerrickRose_FT, DwayneWade_FT])
#

#Free Throw Attempts
KobeBryant_FTA = [819,768,742,564,541,583,451,626,21,241]
JoeJohnson_FTA = [330,314,379,362,269,243,186,161,195,176]
LeBronJames_FTA = [814,701,771,762,773,663,502,535,585,528]
CarmeloAnthony_FTA = [709,568,590,468,612,605,367,512,541,237]
DwightHoward_FTA = [598,666,897,849,816,916,572,721,638,271]
ChrisBosh_FTA = [581,590,559,617,590,471,279,302,272,232]
ChrisPaul_FTA = [465,357,390,524,190,384,302,323,345,321]
KevinDurant_FTA = [256,256,448,524,840,675,501,750,805,171]
DerrickRose_FTA = [205,205,205,250,338,555,239,0,32,187]
DwayneWade_FTA = [803,535,467,771,702,652,297,425,258,370]

#Matrix
#
# <put your code here>
FreeThrowAttempts = np.array([KobeBryant_FTA, JoeJohnson_FTA, LeBronJames_FTA, CarmeloAnthony_FTA, DwightHoward_FTA, ChrisBosh_FTA, ChrisPaul_FTA, KevinDurant_FTA, DerrickRose_FTA, DwayneWade_FTA])
#

In [30]:
type(KobeBryant_G)

numpy.ndarray

In [31]:
type(FreeThrows)

numpy.ndarray

In [16]:
FreeThrowAttempts

array([[819, 768, 742, 564, 541, 583, 451, 626,  21, 241],
       [330, 314, 379, 362, 269, 243, 186, 161, 195, 176],
       [814, 701, 771, 762, 773, 663, 502, 535, 585, 528],
       [709, 568, 590, 468, 612, 605, 367, 512, 541, 237],
       [598, 666, 897, 849, 816, 916, 572, 721, 638, 271],
       [581, 590, 559, 617, 590, 471, 279, 302, 272, 232],
       [465, 357, 390, 524, 190, 384, 302, 323, 345, 321],
       [256, 256, 448, 524, 840, 675, 501, 750, 805, 171],
       [205, 205, 205, 250, 338, 555, 239,   0,  32, 187],
       [803, 535, 467, 771, 702, 652, 297, 425, 258, 370]])

In [17]:
import warnings
warnings.filterwarnings('ignore')
FreeThrowAttempts / Games

array([[ 10.2375    ,   9.97402597,   9.04878049,   6.87804878,
          7.4109589 ,   7.1097561 ,   7.77586207,   8.02564103,
          3.5       ,   6.88571429],
       [  4.02439024,   5.50877193,   4.62195122,   4.58227848,
          3.53947368,   3.375     ,   3.1       ,   2.23611111,
          2.46835443,   2.2       ],
       [ 10.30379747,   8.98717949,  10.28      ,   9.40740741,
         10.17105263,   8.39240506,   8.09677419,   7.03947368,
          7.5974026 ,   7.65217391],
       [  8.8625    ,   8.73846154,   7.66233766,   7.09090909,
          8.86956522,   7.85714286,   6.67272727,   7.64179104,
          7.02597403,   5.925     ],
       [  7.29268293,   8.12195122,  10.93902439,  10.74683544,
          9.95121951,  11.74358974,  10.59259259,   9.48684211,
          8.98591549,   6.6097561 ],
       [  8.3       ,   8.55072464,   8.34328358,   8.01298701,
          8.42857143,   6.11688312,   4.89473684,   4.08108108,
          3.44303797,   5.27272727],
       [  

In [18]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = 10, 4

In [25]:
FreeThrowAttemptsPerGame = np.matrix.round(FreeThrowAttempts / Games)
type(FreeThrowAttemptsPerGame)

numpy.ndarray

In [28]:
FreeThrowAttemptsPerGame

array([[ 10.,  10.,   9.,   7.,   7.,   7.,   8.,   8.,   4.,   7.],
       [  4.,   6.,   5.,   5.,   4.,   3.,   3.,   2.,   2.,   2.],
       [ 10.,   9.,  10.,   9.,  10.,   8.,   8.,   7.,   8.,   8.],
       [  9.,   9.,   8.,   7.,   9.,   8.,   7.,   8.,   7.,   6.],
       [  7.,   8.,  11.,  11.,  10.,  12.,  11.,   9.,   9.,   7.],
       [  8.,   9.,   8.,   8.,   8.,   6.,   5.,   4.,   3.,   5.],
       [  6.,   6.,   5.,   7.,   4.,   5.,   5.,   5.,   6.,   4.],
       [  7.,   7.,   6.,   7.,  10.,   9.,   8.,   9.,  10.,   6.],
       [  5.,   5.,   5.,   3.,   4.,   7.,   6.,  nan,   3.,   4.],
       [ 11.,  10.,   9.,  10.,   9.,   9.,   6.,   6.,   5.,   6.]])

In [26]:
def myPlot(PlayerList):
    Col = {"KobeBryant":"Black","JoeJohnson":"Red","LeBronJames":"Green","CarmeloAnthony":"Blue","DwightHoward":"Pink","ChrisBosh":"Magenta","ChrisPaul":"Yellow","KevinDurant":"Indigo","DerrickRose":"Violet","DwayneWade":"Orange"}
    Mar = {"KobeBryant":"s","JoeJohnson":"o","LeBronJames":"^","CarmeloAnthony":"D","DwightHoward":"s","ChrisBosh":"o","ChrisPaul":"^","KevinDurant":"s","DerrickRose":"^","DwayneWade":"o"}
    for name in PlayerList:
        plt.plot(PlayerList[Pdict[name]], c=Col[name], ls='--', marker=Mar[name], ms='7', label=name)
    plt.legend(loc='upper left', bbox_to_anchor=(1,1))
    plt.xticks(list(range(0, 10)), Seasons, rotation='vertical')
    plt.show()

In [27]:
myPlot(FreeThrowAttemptsPerGame)

TypeError: unhashable type: 'numpy.ndarray'